FROM n8nio/n8n

ENV N8N_USER_MANAGEMENT_DISABLED=true
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=tamaraSecure123
ENV N8N_ENCRYPTION_KEY=w92WtbYkjL0cTPN6ZfRCjwX3N1gqBLz7

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=aws-0-eu-central-1.pooler.supabase.com
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=postgres
ENV DB_POSTGRESDB_USER=postgres.rzxviduwxkbwtwpvqtax
ENV DB_POSTGRESDB_PASSWORD=supersecretpassword123!!!

ENV N8N_HOST=n8n-1-futc.onrender.com
ENV WEBHOOK_TUNNEL_URL=https://n8n-1-futc.onrender.com
ENV N8N_PROTOCOL=https
ENV N8N_PORT=5678

EXPOSE 5678
CMD ["n8n"]
